;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.10
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package #:cl-libqmlbind)



(cffi:defcfun ("qmlbind_application_new" #.(lispify "qmlbind_application_new" 'function)) :pointer
  (argc :int)
  (argv :pointer))

(cffi:defcfun ("qmlbind_application_instance" #.(lispify "qmlbind_application_instance" 'function)) :pointer)

(cffi:defcfun ("qmlbind_application_release" #.(lispify "qmlbind_application_release" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_application_exec" #.(lispify "qmlbind_application_exec" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_application_exit" #.(lispify "qmlbind_application_exit" 'function)) :void
  (returnCode :int))

(cffi:defcfun ("qmlbind_process_events" #.(lispify "qmlbind_process_events" 'function)) :void)

(cffi:defcfun ("qmlbind_next_tick" #.(lispify "qmlbind_next_tick" 'function)) :void
  (callback :pointer)
  (data :pointer))

(cffi:defcfun ("qmlbind_component_new" #.(lispify "qmlbind_component_new" 'function)) :pointer
  (engine :pointer))

(cffi:defcfun ("qmlbind_component_release" #.(lispify "qmlbind_component_release" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_component_load_path" #.(lispify "qmlbind_component_load_path" 'function)) :void
  (self :pointer)
  (path :string))

(cffi:defcfun ("qmlbind_component_load_url" #.(lispify "qmlbind_component_load_url" 'function)) :void
  (self :pointer)
  (url :string))

(cffi:defcfun ("qmlbind_component_set_data" #.(lispify "qmlbind_component_set_data" 'function)) :void
  (self :pointer)
  (data :string)
  (path :string))

(cffi:defcfun ("qmlbind_component_get_error_string" #.(lispify "qmlbind_component_get_error_string" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("qmlbind_component_create" #.(lispify "qmlbind_component_create" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("qmlbind_engine_new" #.(lispify "qmlbind_engine_new" 'function)) :pointer)

(cffi:defcfun ("qmlbind_engine_release" #.(lispify "qmlbind_engine_release" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_engine_eval" #.(lispify "qmlbind_engine_eval" 'function)) :pointer
  (self :pointer)
  (str :string)
  (fileName :string)
  (lineNumber :int))

(cffi:defcfun ("qmlbind_engine_get_global_object" #.(lispify "qmlbind_engine_get_global_object" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("qmlbind_engine_new_object" #.(lispify "qmlbind_engine_new_object" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("qmlbind_engine_new_array" #.(lispify "qmlbind_engine_new_array" 'function)) :pointer
  (self :pointer)
  (length :int))

(cffi:defcfun ("qmlbind_engine_new_wrapper" #.(lispify "qmlbind_engine_new_wrapper" 'function)) :pointer
  (self :pointer)
  (metaclass :pointer)
  (object :pointer))

(cffi:defcfun ("qmlbind_engine_add_import_path" #.(lispify "qmlbind_engine_add_import_path" 'function)) :void
  (self :pointer)
  (path :string))

(cffi:defcfun ("qmlbind_engine_collect_garbage" #.(lispify "qmlbind_engine_collect_garbage" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_metaclass_new" #.(lispify "qmlbind_metaclass_new" 'function)) :pointer
  (classObject :pointer)
  (className :string)
  (callbacks :pointer))

(cffi:defcfun ("qmlbind_metaclass_release" #.(lispify "qmlbind_metaclass_release" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_metaclass_add_method" #.(lispify "qmlbind_metaclass_add_method" 'function)) :void
  (self :pointer)
  (name :string)
  (arity :int))

(cffi:defcfun ("qmlbind_metaclass_add_signal" #.(lispify "qmlbind_metaclass_add_signal" 'function)) :void
  (self :pointer)
  (name :string)
  (arity :int)
  (params :pointer))

(cffi:defcfun ("qmlbind_metaclass_add_property" #.(lispify "qmlbind_metaclass_add_property" 'function)) :void
  (self :pointer)
  (name :string)
  (notifierSignal :string))

(cffi:defcfun ("qmlbind_metaclass_register" #.(lispify "qmlbind_metaclass_register" 'function)) :int
  (self :pointer)
  (uri :string)
  (versionMajor :int)
  (versionMinor :int)
  (qmlName :string))

(cffi:defcfun ("qmlbind_iterator_new" #.(lispify "qmlbind_iterator_new" 'function)) :pointer
  (object :pointer))

(cffi:defcfun ("qmlbind_iterator_release" #.(lispify "qmlbind_iterator_release" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_iterator_get_key" #.(lispify "qmlbind_iterator_get_key" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("qmlbind_iterator_get_value" #.(lispify "qmlbind_iterator_get_value" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("qmlbind_iterator_next" #.(lispify "qmlbind_iterator_next" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_iterator_has_next" #.(lispify "qmlbind_iterator_has_next" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_plugin_new" #.(lispify "qmlbind_plugin_new" 'function)) :pointer
  (filename :string))

(cffi:defcfun ("qmlbind_plugin_release" #.(lispify "qmlbind_plugin_release" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_plugin_get_error_string" #.(lispify "qmlbind_plugin_get_error_string" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("qmlbind_plugin_get_instance" #.(lispify "qmlbind_plugin_get_instance" 'function)) :pointer
  (self :pointer)
  (engine :pointer))

(cffi:defcfun ("qmlbind_signal_emitter_new" #.(lispify "qmlbind_signal_emitter_new" 'function)) :pointer
  (wrapper :pointer))

(cffi:defcfun ("qmlbind_signal_emitter_emit" #.(lispify "qmlbind_signal_emitter_emit" 'function)) :void
  (self :pointer)
  (signal_name :string)
  (argc :int)
  (argv :pointer))

(cffi:defcfun ("qmlbind_signal_emitter_get_engine" #.(lispify "qmlbind_signal_emitter_get_engine" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("qmlbind_signal_emitter_release" #.(lispify "qmlbind_signal_emitter_release" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_string_get_chars" #.(lispify "qmlbind_string_get_chars" 'function)) :string
  (self :pointer))

(cffi:defcfun ("qmlbind_string_get_length" #.(lispify "qmlbind_string_get_length" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_string_release" #.(lispify "qmlbind_string_release" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_value_new_undefined" #.(lispify "qmlbind_value_new_undefined" 'function)) :pointer)

(cffi:defcfun ("qmlbind_value_new_null" #.(lispify "qmlbind_value_new_null" 'function)) :pointer)

(cffi:defcfun ("qmlbind_value_release" #.(lispify "qmlbind_value_release" 'function)) :void
  (self :pointer))

(cffi:defcfun ("qmlbind_value_clone" #.(lispify "qmlbind_value_clone" 'function)) :pointer
  (other :pointer))

(cffi:defcfun ("qmlbind_value_is_equal" #.(lispify "qmlbind_value_is_equal" 'function)) :int
  (value1 :pointer)
  (value2 :pointer))

(cffi:defcfun ("qmlbind_value_is_identical" #.(lispify "qmlbind_value_is_identical" 'function)) :int
  (value1 :pointer)
  (value2 :pointer))

(cffi:defcfun ("qmlbind_value_is_undefined" #.(lispify "qmlbind_value_is_undefined" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_is_null" #.(lispify "qmlbind_value_is_null" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_is_boolean" #.(lispify "qmlbind_value_is_boolean" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_is_number" #.(lispify "qmlbind_value_is_number" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_is_string" #.(lispify "qmlbind_value_is_string" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_is_object" #.(lispify "qmlbind_value_is_object" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_is_array" #.(lispify "qmlbind_value_is_array" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_is_function" #.(lispify "qmlbind_value_is_function" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_is_error" #.(lispify "qmlbind_value_is_error" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_is_wrapper" #.(lispify "qmlbind_value_is_wrapper" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_new_boolean" #.(lispify "qmlbind_value_new_boolean" 'function)) :pointer
  (value :int))

(cffi:defcfun ("qmlbind_value_get_boolean" #.(lispify "qmlbind_value_get_boolean" 'function)) :int
  (self :pointer))

(cffi:defcfun ("qmlbind_value_new_number" #.(lispify "qmlbind_value_new_number" 'function)) :pointer
  (value :double))

(cffi:defcfun ("qmlbind_value_get_number" #.(lispify "qmlbind_value_get_number" 'function)) :double
  (self :pointer))

(cffi:defcfun ("qmlbind_value_new_string" #.(lispify "qmlbind_value_new_string" 'function)) :pointer
  (length :int)
  (value :string))

(cffi:defcfun ("qmlbind_value_new_string_cstr" #.(lispify "qmlbind_value_new_string_cstr" 'function)) :pointer
  (value :string))

(cffi:defcfun ("qmlbind_value_get_string" #.(lispify "qmlbind_value_get_string" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("qmlbind_value_get_property" #.(lispify "qmlbind_value_get_property" 'function)) :pointer
  (self :pointer)
  (key :string))

(cffi:defcfun ("qmlbind_value_set_property" #.(lispify "qmlbind_value_set_property" 'function)) :void
  (self :pointer)
  (key :string)
  (value :pointer))

(cffi:defcfun ("qmlbind_value_delete_property" #.(lispify "qmlbind_value_delete_property" 'function)) :int
  (self :pointer)
  (key :string))

(cffi:defcfun ("qmlbind_value_has_property" #.(lispify "qmlbind_value_has_property" 'function)) :int
  (self :pointer)
  (key :string))

(cffi:defcfun ("qmlbind_value_has_own_property" #.(lispify "qmlbind_value_has_own_property" 'function)) :int
  (self :pointer)
  (key :string))

(cffi:defcfun ("qmlbind_value_get_prototype" #.(lispify "qmlbind_value_get_prototype" 'function)) :pointer
  (self :pointer))

(cffi:defcfun ("qmlbind_value_set_prototype" #.(lispify "qmlbind_value_set_prototype" 'function)) :void
  (self :pointer)
  (proto :pointer))

(cffi:defcfun ("qmlbind_value_has_index" #.(lispify "qmlbind_value_has_index" 'function)) :int
  (self :pointer)
  (index :int))

(cffi:defcfun ("qmlbind_value_get_array_item" #.(lispify "qmlbind_value_get_array_item" 'function)) :pointer
  (self :pointer)
  (index :int))

(cffi:defcfun ("qmlbind_value_set_array_item" #.(lispify "qmlbind_value_set_array_item" 'function)) :void
  (self :pointer)
  (index :int)
  (property :pointer))

(cffi:defcfun ("qmlbind_value_call" #.(lispify "qmlbind_value_call" 'function)) :pointer
  (self :pointer)
  (argc :int)
  (argv :pointer))

(cffi:defcfun ("qmlbind_value_call_constructor" #.(lispify "qmlbind_value_call_constructor" 'function)) :pointer
  (function :pointer)
  (argc :int)
  (argv :pointer))

(cffi:defcfun ("qmlbind_value_call_with_instance" #.(lispify "qmlbind_value_call_with_instance" 'function)) :pointer
  (self :pointer)
  (instance :pointer)
  (argc :int)
  (argv :pointer))

(cffi:defcfun ("qmlbind_value_unwrap" #.(lispify "qmlbind_value_unwrap" 'function)) :pointer
  (self :pointer))


